// THIS IS GENERATED BY CHATGPT
export interface Ability {
    ability: {
      name: string;
      url: string;
    };
    is_hidden: boolean;
    slot: number;
  }
  
  export interface Cry {
    latest: string;
    legacy: string;
  }
  
  export interface Form {
    name: string;
    url: string;
  }
  
  export interface GameIndex {
    game_index: number;
    version: {
      name: string;
      url: string;
    };
  }
  
  export interface Move {
    move: {
      name: string;
      url: string;
    };
  }
  
  export interface Species {
    name: string;
    url: string;
  }
  
  export interface Sprite {
    back_default: string | null;
    back_female: string | null;
    back_shiny: string | null;
    back_shiny_female: string | null;
    front_default: string;
    front_female: string | null;
    front_shiny: string | null;
    front_shiny_female: string | null;
  }
  
  export interface Stat {
    base_stat: number;
    effort: number;
    stat: {
      name: string;
      url: string;
    };
  }
  
  export interface Type {
    slot: number;
    type: {
      name: string;
      url: string;
    };
  }
  
  export interface Pokemon {
    id: number;
    name: string;
    base_experience: number;
    height: number;
    weight: number;
    is_default: boolean;
    location_area_encounters: string;
    abilities: Ability[];
    cries: Cry;
    forms: Form[];
    game_indices: GameIndex[];
    moves: Move[];
    species: Species;
    sprites: Sprite;
    stats: Stat[];
    types: Type[];
  }

